name: AQI Automation Pipeline

on:
  schedule:
    - cron: "0 * * * *"  # Hourly: feature scripts
    - cron: "0 0 * * *"  # Daily: training
  workflow_dispatch:      # Manual trigger

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pymongo python-dotenv scikit-learn pandas requests

      - name: Set Env Variables
        run: |
          echo "AIR_POLLUTION_API=${{ secrets.AIR_POLLUTION_API }}" >> $GITHUB_ENV
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

  hourly_feature_pipeline:
    name: Feature Pipeline Hourly
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'schedule' && github.event.schedule == '0 * * * *'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Feature Scripts
        run: |
          python fetch_historical_pollution.py
          python fetch_historical_weather_and_merge.py

  daily_training_pipeline:
    name: Training Pipeline Daily
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Training Script
        run: |
          python train_model.py

      - name: Run Prediction Script
        run: |
          python predict_aqi.py
